name: CI/CD Pipeline with EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project2:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/project2:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with SSH (Debug Enabled)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling Docker images..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/project2:latest

            echo "Stopping and removing existing containers..."
            docker stop project2 || true
            docker rm project2 || true

            echo "Creating Docker network..."
            docker network create my-network || true

            echo "Starting project2 container..."
            docker run -d --name project2 --network my-network -p 80:3000 -v /path/to/data:/app/data ${{ secrets.DOCKER_USERNAME }}/project2:latest

          debug: true
